### ISSUE TITLE
Touching a flagpole on the same frame as the static triggering softlocks the level

### ISSUE THREAD

**Issue by Caylie-C** [Ndymario/Ordinary-NSMB-Mod#11]
Although this is an extremely unlikely circumstance, doing this will cause the static to remain on screen indefinitely.

**Comment by Ndymario** [comment]
This is insanely hard to get happen in game, good catch. This will be tricky to fix, but I will try.

**Comment by Ndymario** [comment]
This is hard to test, but I believe this was the root of the problem. Now the controller can "tick" if it is currently rendering static.

This has the side effect of seeing the "course clear" animation in spooky mode. This is technically a bug, but I don't think it's worth spending the time to fix something that's ultimately a visual bug.
