### ISSUE TITLE
Luigi appears recursively during vertical autoscroll segment in World 7-2 and 8-6

### ISSUE THREAD

**Issue by Caylie-C** [Ndymario/Ordinary-NSMB-Mod#12]
As soon as the static appears in Worlds 7-2 and 8-6, Luigi will wrap around the screen multiple times at an abnormal speed until he's close enough to Mario that he'd be normally visible, at which his speed will decrease to its regular value. This effect is only visual, and Luigi will pass through Mario multiple times in this glitched, sped-up state.

**Comment by Ndymario** [comment]
This is a side effect of level wrap as I lazily tie the chaser's position to the spooky timer. Easy fix is to hide the NSBTX until it should be visible. Will look into.

**Comment by Ndymario** [comment]
This has been fixed! This fix will be released with v2.2.1.
