### ISSUE TITLE
Hitting flip panels on grates creates collision issues with enemies

### ISSUE THREAD

**Issue by Caylie-C** [Ndymario/Ordinary-NSMB-Mod#9]
When behind the layer for grates (from hitting flip panels an odd number of times,) some enemies become intangible in "spooky mode." Seen best in World 3-Tower after hitting the flip panel around the first set of Amps and attempting to interact with the Red Koopa Troopa next to the brick gap on the floor.

**Comment by Ndymario** [comment]
I never noticed this, thanks for the report. Will look into.

**Comment by Ndymario** [comment]
@Caylie-C I'm having trouble reproducing this; I'm able to interact with the enemies fine. Do you remember more exact steps to trigger this?

**Comment by Caylie-C** [comment]
So it turns out this behavior is in the original game and I just never noticed, it isn't a necessary bug to fix. To clarify regardless, after a bit of testing, it seems to only happen before landing on the ground (or while being behind a grate tile even if not climbing on it?) The damage hitbox still functions but if you try to jump directly onto the red koopa troopa from the backside of the grate, regardless of angle, you'll phase right though it and get damaged instead. Still, false alarm, apologies for reporting this one.

**Comment by Ndymario** [comment]
All good, thanks for responding!
